name: GitHub Actions Test
on:
  push:
    branches:
      - master
jobs:
  check-last-changes:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token for authentication
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create
        run: |
          gh pr create --title "Pull request title" --body "Pull request body"