name: Check Last Changes

on:
  push:
    branches:
      - master

jobs:
  check-last-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Get changes
        id: get_changes
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changes::$CHANGES"

      - name: Store changes in variable
        run: | 
          echo "Changes: ${{ steps.get_changes.outputs.changes }}"

