name: GitHub Actions Test
on:
  push:
    branches:
      - master
jobs:
  check-last-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Get changes
        id: get_changes
        run: |
          CHANGES=$(git fetch --unshallow origin master && git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changes::$CHANGES"

      - name: Store changes in variable
        run: | 
          echo "Changes: ${{ steps.get_changes.outputs.changes }}"

